/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface EscrowSystemInterface extends utils.Interface {
  functions: {
    "admin()": FunctionFragment;
    "cancelEscrow(bytes32,string)": FunctionFragment;
    "changeAdmin(address)": FunctionFragment;
    "escrows(bytes32)": FunctionFragment;
    "getEscrow(bytes32)": FunctionFragment;
    "lockFund(bytes32,address,string)": FunctionFragment;
    "releaseFund(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "admin"
      | "cancelEscrow"
      | "changeAdmin"
      | "escrows"
      | "getEscrow"
      | "lockFund"
      | "releaseFund"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelEscrow",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "changeAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "lockFund",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFund",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockFund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseFund",
    data: BytesLike
  ): Result;

  events: {
    "FundCancelled(bytes32,address,uint256,string)": EventFragment;
    "FundLocked(bytes32,address,address,uint256,string)": EventFragment;
    "FundReleased(bytes32,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FundCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundLocked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundReleased"): EventFragment;
}

export interface FundCancelledEventObject {
  escrowId: string;
  payer: string;
  amount: BigNumber;
  reason: string;
}
export type FundCancelledEvent = TypedEvent<
  [string, string, BigNumber, string],
  FundCancelledEventObject
>;

export type FundCancelledEventFilter = TypedEventFilter<FundCancelledEvent>;

export interface FundLockedEventObject {
  escrowId: string;
  payer: string;
  payee: string;
  amount: BigNumber;
  schoolId: string;
}
export type FundLockedEvent = TypedEvent<
  [string, string, string, BigNumber, string],
  FundLockedEventObject
>;

export type FundLockedEventFilter = TypedEventFilter<FundLockedEvent>;

export interface FundReleasedEventObject {
  escrowId: string;
  payee: string;
  amount: BigNumber;
}
export type FundReleasedEvent = TypedEvent<
  [string, string, BigNumber],
  FundReleasedEventObject
>;

export type FundReleasedEventFilter = TypedEventFilter<FundReleasedEvent>;

export interface EscrowSystem extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EscrowSystemInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    admin(overrides?: CallOverrides): Promise<[string]>;

    cancelEscrow(
      escrowId: PromiseOrValue<BytesLike>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changeAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    escrows(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        boolean,
        boolean,
        string,
        BigNumber,
        BigNumber
      ] & {
        payer: string;
        payee: string;
        amount: BigNumber;
        isLocked: boolean;
        isReleased: boolean;
        schoolId: string;
        lockedAt: BigNumber;
        releasedAt: BigNumber;
      }
    >;

    getEscrow(
      escrowId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean, boolean, string] & {
        payer: string;
        payee: string;
        amount: BigNumber;
        isLocked: boolean;
        isReleased: boolean;
        schoolId: string;
      }
    >;

    lockFund(
      escrowId: PromiseOrValue<BytesLike>,
      payee: PromiseOrValue<string>,
      schoolId: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    releaseFund(
      escrowId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  admin(overrides?: CallOverrides): Promise<string>;

  cancelEscrow(
    escrowId: PromiseOrValue<BytesLike>,
    reason: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changeAdmin(
    newAdmin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  escrows(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      BigNumber,
      boolean,
      boolean,
      string,
      BigNumber,
      BigNumber
    ] & {
      payer: string;
      payee: string;
      amount: BigNumber;
      isLocked: boolean;
      isReleased: boolean;
      schoolId: string;
      lockedAt: BigNumber;
      releasedAt: BigNumber;
    }
  >;

  getEscrow(
    escrowId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, boolean, boolean, string] & {
      payer: string;
      payee: string;
      amount: BigNumber;
      isLocked: boolean;
      isReleased: boolean;
      schoolId: string;
    }
  >;

  lockFund(
    escrowId: PromiseOrValue<BytesLike>,
    payee: PromiseOrValue<string>,
    schoolId: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  releaseFund(
    escrowId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    admin(overrides?: CallOverrides): Promise<string>;

    cancelEscrow(
      escrowId: PromiseOrValue<BytesLike>,
      reason: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    changeAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    escrows(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        boolean,
        boolean,
        string,
        BigNumber,
        BigNumber
      ] & {
        payer: string;
        payee: string;
        amount: BigNumber;
        isLocked: boolean;
        isReleased: boolean;
        schoolId: string;
        lockedAt: BigNumber;
        releasedAt: BigNumber;
      }
    >;

    getEscrow(
      escrowId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean, boolean, string] & {
        payer: string;
        payee: string;
        amount: BigNumber;
        isLocked: boolean;
        isReleased: boolean;
        schoolId: string;
      }
    >;

    lockFund(
      escrowId: PromiseOrValue<BytesLike>,
      payee: PromiseOrValue<string>,
      schoolId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    releaseFund(
      escrowId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "FundCancelled(bytes32,address,uint256,string)"(
      escrowId?: PromiseOrValue<BytesLike> | null,
      payer?: PromiseOrValue<string> | null,
      amount?: null,
      reason?: null
    ): FundCancelledEventFilter;
    FundCancelled(
      escrowId?: PromiseOrValue<BytesLike> | null,
      payer?: PromiseOrValue<string> | null,
      amount?: null,
      reason?: null
    ): FundCancelledEventFilter;

    "FundLocked(bytes32,address,address,uint256,string)"(
      escrowId?: PromiseOrValue<BytesLike> | null,
      payer?: PromiseOrValue<string> | null,
      payee?: PromiseOrValue<string> | null,
      amount?: null,
      schoolId?: null
    ): FundLockedEventFilter;
    FundLocked(
      escrowId?: PromiseOrValue<BytesLike> | null,
      payer?: PromiseOrValue<string> | null,
      payee?: PromiseOrValue<string> | null,
      amount?: null,
      schoolId?: null
    ): FundLockedEventFilter;

    "FundReleased(bytes32,address,uint256)"(
      escrowId?: PromiseOrValue<BytesLike> | null,
      payee?: PromiseOrValue<string> | null,
      amount?: null
    ): FundReleasedEventFilter;
    FundReleased(
      escrowId?: PromiseOrValue<BytesLike> | null,
      payee?: PromiseOrValue<string> | null,
      amount?: null
    ): FundReleasedEventFilter;
  };

  estimateGas: {
    admin(overrides?: CallOverrides): Promise<BigNumber>;

    cancelEscrow(
      escrowId: PromiseOrValue<BytesLike>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changeAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    escrows(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEscrow(
      escrowId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockFund(
      escrowId: PromiseOrValue<BytesLike>,
      payee: PromiseOrValue<string>,
      schoolId: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    releaseFund(
      escrowId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cancelEscrow(
      escrowId: PromiseOrValue<BytesLike>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changeAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    escrows(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEscrow(
      escrowId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockFund(
      escrowId: PromiseOrValue<BytesLike>,
      payee: PromiseOrValue<string>,
      schoolId: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    releaseFund(
      escrowId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
